objective_2/admin/urls.py
from django.contrib import admin
from django.urls import path

from .views import table_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tables/', table_list, name='table_list'),
]

objective_2/audit/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'audit'

urlpatterns = [
    path('', views.auditHome, name='auditHome'),

    path('login/', views.LoginView, name='login'),    
    path('logout/', views.LogoutView, name='logout'),    
    path('list/', views.list, name='list'),
    

    path('create/', views.create_waste_entry, name='create'),
    path('entries/<int:waste_entry_id>/delete/', views.delete_waste_entry, name='delete_entry'),
    path('entries/', views.waste_entries, name='entries'),

    path('items/<int:waste_entry_id>/create/', views.create_waste_item, name='create_item'),
    path('items/<int:waste_item_id>/delete/', views.delete_waste_item, name='delete_item'),
    path('items/<int:waste_entry_id>/', views.waste_items, name='items'),
    
    path('donate', views.donate, name='donate'),
   path('donate/past', views.donate_read, name = 'donate_read'),
    path('donate/update', views.donate_update, name = 'donate_update'),
    path('donate/delete', views.donate_delete, name = 'donate_delete'),
    path('', views.accounts, name='accounts'),
    path('recipes/', views.recipe_list, name='recipe_list'),
    path('add_food/',views.add_food,name='add_food'),
    path('recipefoodsave.html/',views.savefood,name='savefoodss'),
   # path('initiate-payment/', views.initiate_payment, name='initiate_payment'),
   # path('complete-payment/<int:payment_id>/', views.complete_payment, name='complete_payment'),
]

objective_2/objective_2/urls.py
from django.urls import include, path

urlpatterns = [
    path('admin_console/', include('admin_console.urls')),
    path('', include('users.urls')),
    path('audit/', include('audit.urls')),
    path('accounts/', include('audit.urls')),

]

objective_2/users/urls.py
from django.urls import path, include
from django.contrib import admin
#from django.contrib.auth import views as auth_views

from . import views
#from audit.views import views
# from accounts import views


urlpatterns = [

    path('', views.index, name='index'),
    path('data_model', views.wastage, name='data_model'),
    path('calculator', views.Calindex, name='calculator'),
    path('analyze', views.calculator, name='calculator_analyzed'),
    path('items/<id>', views.detail, name='items'),
    path('<invalid>', views.invalid, name='invalid'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('signup/', views.Signup, name='signup'),
    path('login/', views.LoginView, name='login'), 
    path('logout/', views.LogoutView, name='logout'), 
    #path('audit/', views.audit, name='audit'),
    path('admin/', admin.site.urls),
]

objective_2/users/models.py
from django.db import models
from django.core.validators import MinLengthValidator


    

objective_2/users/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, redirect, reverse
from . import items
from django.contrib.auth import authenticate, login, logout
from .info import Info
from audit.models import  WasteItems

def index(request):
    return render(request, 'users/index.html')

def invalid(request, invalid):
    return render(request, 'users/notfound.html')

def data_model(request):
    return render(request, 'users/data_model.html')

def header(request):
    return render(request, 'header.html',{})

def footer(request):
    return render(request, 'footer.html',{})
    


# Old Item Pages (We should delete the commented out section)

def impacts(request):
   return HttpResponse(loader.get_template('users/facts.html').render())

def Calindex(request):
    return render(request, 'users/CalculateForm.html')
def calculator(request):
    try:
        number_of_people=int(request.GET.get('number_of_people'))
        kilos=int(request.GET.get('kilos'))
        frequency_of_buying=int(request.GET.get('frequency_of_buying'))
        age=int(request.GET.get('age'))
        

        food_Waste= (kilos*frequency_of_buying)/(number_of_people)
        if food_Waste<5:


            params = {'purpose': 'calculated food waste', 'analyzed_text': int(food_Waste)}

            return render(request,'users/CalculatorAnalyse.html',params)
        else:
            params = {'purpose': 'calculated food waste', 'analyzed_text': int(food_Waste)}
            return render(request,'users/CalculatorAnalyse1.html',params)
            
    except: 
        return render(render, "users/notfound.html")

# New function to handle item url lookup
# Details
def detail(request, id):
    page = 'users/details.html'
    try:
        context = {'item':items.Item_Class.find(id)}
        #page = "users/{}.html".format(id)
    except:
        context = {}
        page = "users/notfound.html"
    return render(request, page, context)



def create_wastage():
    Waste=[]
    Waste.append((Info("Perth",3000,"2000 People")))
    Waste.append((Info("Melbourne",54000,"100000 People")))
    Waste.append((Info("Sydney",58000,"120000 People")))
    Waste.append((Info("Darwin",2322,"1200 People")))
    
    return Waste
    

    
def wastage(request):
    context={
        'var':create_wastage()
    }
    return render(request,'users/data_model.html',context)



def LoginView(request):
    login = reverse("audit:login")
    return redirect(login)
    
def LogoutView(request):
    logout = reverse("audit:logout")
    return redirect(logout)

def Signup(request):
    return render(request, 'users/signup.html',{})

objective_2/users/templates/users/CalculateForm.html
{% extends 'users/__base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <style>
      .titledoc {
        color: rgb(4, 4, 5);
        align-items: center;
      }
      .form {
        
        justify-content: center;
        font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
        background-color: rgb(139, 138, 150);
      }
      .formcontent {
        font-family:  Tahoma, Geneva, Verdana, sans;
        color: white;
      }
      .submit{
        display: flex;
        justify-content: center;
      }
    </style>
  </head>
  <body>
    {% block content %}
    <div class="form">
      <h1 class="titledoc">This is a sample food waste calculator</h1>

      <form action="/analyze" method="get">
        <div class="formcontents" >
          How many People did you buy food for? <br />
          <input type="number" name="number_of_people" /><br />
        </div>
        <div class="formcontents">
          How many kilos did you throw Away?<br />
          <input type="number" name="kilos" /><br />
        </div>
        <div class="formcontents">
          How many times in a week do you buy fresh food?<br />
          <input type="number" name="frequency_of_buying" /><br />
        </div>
        <div class="formcontents">
          How old are you?<br />
          <input type="number" name="age" />
        </div>
        <br />
        <br />
        <div class="submit">
        <input type="submit" /></div>
      </form>
    </div>
    {% endblock %}
  </body>
</html>

objective_2/users/templates/users/CalculatorAnalyse.html
{% extends 'users/__base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Analyzing Your Text...</title>
    <link rel="stylesheet" href="style.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
  </head>
  <style>
    .bootstrap {
      padding-top:14px;
    }
    .accordion accordion-flush{
      background-color: rgb(89, 177, 177);

    }
  </style>
  <body>
    {% block content %}
    <div class="titletext">
      <h1 class="titletext">The carbon Imprint for {{ purpose }}</h1>
    </div>

    <div class="content">
      <div class="info">
        <span>
          The expected food waste is {{ analyzed_text }} Kgs per week</span
        >
      </div>
    </div>
    <div class="content1">      
      <span>
        See the carbon Impact it created could be utilised instead for:</span>
      <div class="bootstrap">
        <div class="accordion accordion-flush" id="accordionFlushExample">
          <div class="accordion-item-black">
            <h2 class="accordion-header">
              <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flush-collapseOne"
                aria-expanded="false"
                aria-controls="flush-collapseOne"
              >
                Fuel your car for 6 kilometers
              </button>
            </h2>
            <div
              id="flush-collapseOne"
              class="accordion-collapse collapse"
              data-bs-parent="#accordionFlushExample"
            >
              <div class="accordion-body">
                You could use your car from palmerston to Jetty for free!!
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header">
              <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flush-collapseTwo"
                aria-expanded="false"
                aria-controls="flush-collapseTwo"
              >
                Power your Computer for an hour
              </button>
            </h2>
            <div
              id="flush-collapseTwo"
              class="accordion-collapse collapse"
              data-bs-parent="#accordionFlushExample"
            >
              <div class="accordion-body">
                Could have generated more than 10 Watt of power
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header">
              <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flush-collapseThree"
                aria-expanded="false"
                aria-controls="flush-collapseThree"
              >
                Waste generated to almost 5 McSpicy burgers
              </button>
            </h2>
            <div
              id="flush-collapseThree"
              class="accordion-collapse collapse"
              data-bs-parent="#accordionFlushExample"
            >
              <div class="accordion-body">
                You could have eaten 5 burgers for free!!
              </div>
            </div>
          </div>
        </div>
      </div>
   
    </div>
    {% endif %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"
    ></script>
    {% endblock %}
  </body>
</html>

objective_2/users/templates/users/CalculatorAnalyse1.html
{% extends 'users/__base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Analyzing Your Text...</title>
    <link rel="stylesheet" href="style.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
  </head>
  <style>
    .bootstrap {
      padding-top:14px;
    }
    .accordion accordion-flush{
      background-color: rgb(89, 177, 177);

    }
  </style>
  <body>
    {% block content %}
    <div class="titletext">
      <h1 class="titletext">The carbon Imprint for {{ purpose }}</h1>
    </div>

    <div class="content">
      <div class="info">
        <span>
          The expected food waste is {{ analyzed_text }} Kgs per week</span
        >
      </div>
    </div>
    <div class="content1">
      
     
      <span>
        See the carbon Impact it created could be utilised instead for:</span>
      <div class="bootstrap">
        <div class="accordion accordion-flush" id="accordionFlushExample">
          <div class="accordion-item-black">
            <h2 class="accordion-header">
              <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flush-collapseOne"
                aria-expanded="false"
                aria-controls="flush-collapseOne"
              >
                Fuel your car for 3 kilometers
              </button>
            </h2>
            <div
              id="flush-collapseOne"
              class="accordion-collapse collapse"
              data-bs-parent="#accordionFlushExample"
            >
              <div class="accordion-body">
                You could use your car and had the visit to the beach for free
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header">
              <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flush-collapseTwo"
                aria-expanded="false"
                aria-controls="flush-collapseTwo"
              >
                Power your Oven for 20 mins
              </button>
            </h2>
            <div
              id="flush-collapseTwo"
              class="accordion-collapse collapse"
              data-bs-parent="#accordionFlushExample"
            >
              <div class="accordion-body">
                Imagine having your favourite freshly baked oven chips for
                free!!
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header">
              <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flush-collapseThree"
                aria-expanded="false"
                aria-controls="flush-collapseThree"
              >
                Saved one little Egg
              </button>
            </h2>
            <div
              id="flush-collapseThree"
              class="accordion-collapse collapse"
              data-bs-parent="#accordionFlushExample"
            >
              <div class="accordion-body">
                With your food waste carbon imprint, you could have saved a
                chicken's child 
              </div>
            </div>
          </div>
        </div>
      </div>
    

      
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"
    ></script>
    {% endblock %}
  </body>
</html>

objective_2/users/templates/users/__base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static 'users/css/styles.css' %}">
    {% block title %}<title>Food Waste</title>{% endblock %}
</head>
<body>
    <header>
        {% include 'users/header.html' %}
    </header>
    <main>
        {% block content %}{% endblock%}
    </main>
    <footer>
        {% include 'users/footer.html' %}
    </footer>
</body>
</html>

objective_2/users/templates/users/data_model.html
{% extends 'users/__base.html' %}

{% block content %}

<h1>Data Model</h1>

<h2>Base Data Model for Items</h2>
<table style="margin-bottom:15px;">
    <th>
        <tr>
            <th>Field</th>
            <th>Purpose</th>
            <th>Data type</th>
            <th>Constraints</th>
        </tr>
    </th>

    <tb>
        <tr>
            <td>id</td><td>primary key of table</td><td>numeric</td><td>primary key</td>
        </tr>
        <tr>
            <td>name</td><td>used to resolve item url</td><td>text</td><td>unique key</td>
        </tr>
        <tr>
            <td>title</td><td>title of item</td><td>text</td><td></td>
        </tr>
        <tr>
            <td>content</td><td>display item's structured html data on webpage</td><td>text</td><td></td>
        </tr>
        <tr>
            <td>images</td><td>display images of item on webpage</td><td>text</td><td></td>
        </tr>
    </tb>

</table>


<h2>Data model for dynamic items</h2>
<h3>Food Waste Calculator</h3>
<table class="table table-striped-my-7">
    <thead>
        <tr>
            <th scope="col">Sr. no</th>
            <th scope="col">City</th>
            <th scope="col">Food Waste in Kgs</th>
            <th scope="col">Number of people affected </th>
        </tr>
    </thead>
    <tbody>
        {% for info in var %}
        <tr>
            <th scope="row-my-3">{{forloop.counter}}</th>
            <td>{{info.city}}</td>
            <td>{{info.wastage}}</td>
            <td>{{info.impact}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>



<h3>Shopping List Maker (In development)</h3>
<table style="margin-bottom:15px;">
    <th>
    <tr>
        <th>Field</th>
        <th>Purpose</th>
        <th>Data type</th>
        <th>Constraints</th>
    </tr>
    </th>

    <tb>
        <tr>
            <td>user_ID</td>
            <td>used to identify specific user data</td>
            <td>numeric</td>
            <td></td>
        </tr>
        <tr>
            <td>item_id</td>
            <td>Foreign key of base data model for item</td>
            <td>numeric</td>
            <td>Unique Key</td>
        </tr>
        <tr>
            <td>Food_item</td>
            <td>the food item in user shopping list</td>
            <td>text</td>
            <td>user can enter any item</td>
        </tr>
        <tr>
            <td>amount</td>
            <td>number of specific item in shopping list</td>
            <td>numeric</td>
            <td>Maximum 10</td>
        </tr>
    </tb>
</table>


    {% endblock%}

objective_2/users/templates/users/details.html
{% extends "users/__base.html" %}
{% load static %}
{% load index %}            


<link rel="stylesheet" href="{% static 'users/header_style' %}" media= "screen" />

{% block title %}
<title> {{ item.title }} </title>
{% endblock %}

{% block content %}

<h1> {{ item.title }}</h1>
{% for content in item.content %}
<div class="detail content">
    {% if item.images|index:forloop.counter0 %}
    <img class="image detail" src="{% static item.images|index:forloop.counter0 %} " />
    {% endif %}

    {% autoescape off %}
    {{ content }}
    {% endautoescape %}
</div>
{% endfor %}



{% endblock %}


<!--
E.g. Layout

Title

Content 1                           |   Image
                                    |
                                    |
                                    |

Content 2                           |   Image
                                    |
                                    |
                                    |

-->

objective_2/users/templates/users/footer.html
<!--Footer -->
<h4>It is a informative website about food waste and its mitigation</h4> 
<p>Made by <u>HIT237 Group-2.</u></p>

<h5><u> Contact Us: </u><br>(Our student email in CDU)</h5>
<p>Matthew Bonfanti: 349051@students.cdu.edu.au | Arsh Hasan: 353668@students.cdu.edu.au | Joshua Adigun:  356169@students.cdu.edu.au | Meherina Shetu:  316782@students.cdu.edu.au</p>
    

objective_2/users/templates/users/header.html
{% load static %}

{% include 'users/navbar.html' %}

<nav class="nagivation-images">
    <article>
        <img src="{% static 'users/images/cause.png'%}" />
        <h5><a href="{% url 'items' 'impacts'%}">Impacts</a></h5>
        <p>It impacts mainly on economy and environment.</p>
    </article>

    <article>
        {% url 'items' as item_url %}
        <img src="{% static 'users/images/benefit.png'%}" />
        <h5><a href="{% url 'items' 'benefits'%}">Benefits</a></h5>
        <p>Food-waste management is beneficial for environmental,economical,social perspective.</p>
    </article>

    <article>
        <img src="{% static 'users/images/solution.png'%}" />
        <h5><a href="{% url 'items' 'solutions' %}">Food-waste Solution</a></h5>
        <p>We need to solve food waste problem with proper and effective solution.</p>
    </article>

    <article>
        {% url 'calculator' as calculator_url %}
        <img src="{% static 'users/images/calculator.png'%}" />
        <h5><a href="{% url 'calculator' %}">Food Calculator</a></h5>
        <p>With proper use of food calculation we can solve many wastage.</p>
    </article>
</nav>

<h1 class="title">Food-waste:<br>causes and solutions</h1>
<p>This website is about protecting global food chain by raising awareness and educating <br>people about food-waste and discussion about its proper mitigation.</p>

objective_2/users/templates/users/list.html
{% extends "users/__base.html" %}
{% load static %}
{% load index %}

    {% block title %}
    <title>List</title>
    {% endblock %}
    {% block content %}
<h1>Item List</h1>
<p> This page displays a list of all the items required by the project brief.</p>
<h3>List of items for this project are:</h3>
<ul>
    {% for item in item_list %}
    <li>
        <p class="list" style="padding-top:8px; height: 1.5em; background:rgba(0, 0, 0,0.1);">
            <a href="{% url 'items' item.name  %}" style=" color: orange; font-size: 2em;">{{ item.name|upper }}</a>
         - {{ item.title }}
        </p>
    </li>
    {% endfor %}
    <li>
        <p class="list" style="padding-top:8px; height: 1.5em; background:rgba(0, 0, 0,0.1);">
            <a href="{% url 'calculator' %}" style="color: orange; font-size: 2em;">CALCULATOR</a>
            - Calculate the impact of your food waste.
        </p>
    </li>
</ul>
    {% endblock %}

objective_2/users/templates/users/login.html
{% extends "users/__base.html" %}
{% load static %}
{% load index %}


{% block content %}
        
        <div style='margin-top:30px;'>
            <form action="" method="post" id="loginform">
                {% csrf_token %}
                {% if error %}
                <p style='color:red'>{{ error }}</p>
                {% endif %}
            </div>
                <input type='text' name='username'
                    placeholder='username' />
                
                    <input type='password' name='password' placeholder='password' />
                    <button type="submit" form="loginform">Log in</button>
                </div>
                </form>
                
                
            </div>
       
            
    
{% endblock %}

objective_2/users/templates/users/navbar.html
<nav>
    <div class="nav-links">
        <ul>
            <li class="nav-item">
                <a class="nav-link {% if navbar == 'Home' %} active {% endif %}" aria-current="page" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if navbar == 'list' %} active {% endif %}" href="{% url 'audit:list' %}">List</a>
            </li>

            <li class="nav-item" id="log">
                <a class="nav-link {% if navbar == 'login' %} active {% endif %}" href="{% url 'login' %}">Log in</a>
            </li>

            <li class="nav-item" id="log">
                <a class="nav-link {% if navbar == 'loginout' %} active {% endif %}" href="{% url 'logout' %}">Log out</a>
            </li>


            
        </ul>
    </div>
</nav>

objective_2/users/templates/users/notfound.html
{% extends 'users/__base.html' %}

{% block content %}

<h1>Page not found</h1>

<p>We are sorry, we couldn't find the page you requested. </p>

{% endblock%}

objective_2/users/templates/users/signup.html
{% extends "users/__base.html" %}
{% load static %}
{% load index %}

{% block navbar %}
<nav>
   <div class="nav-links">
       <ul>
           <li class="nav-item">
               <a class="nav-link {% if navbar == 'Home' %} active {% endif %}" aria-current="page" href="{% url 'index' %}">Home</a>
           </li>
           <li class="nav-item">
               <a class="nav-link {% if navbar == 'list' %} active {% endif %}" href="{% url 'list' %}">List</a>
           </li>
           <li class="nav-item">
               <a class="nav-link {% if navbar == 'data_model' %} active {% endif %}" href="{% url 'data_model' %}">Data model</a>
           </li>
            <li class="nav-item" id="log">
               <a class="nav-link {% if navbar == 'login' %} active {% endif %}" href="{% url 'logout' %}">Log Out</a>
           </li>
           
            
           <li class="nav-item">
               <a class="nav-link {% if navbar == 'wastelist' %} active {% endif %}" href="{% url 'wastelist' %}">Waste list</a>
           </li>
       </ul>
   </div>
</nav>
{% endblock %}
HI {{ users.user.name}}!
You are logged In



objective_2/users/templates/users/wastelist.html
{% extends "users/__base.html" %}
{% load static %}
{% load index %}

    {% block content %}
    <h1>Waste-list</h1>
    {% for wastelist in wastelist %}
       <strong>{{ wastelist}}</strong> 
       <ul>
        <li>WasteItemID: {{ wastelist.wasteItemID }}</li>
        <li>WasteEntryID: {{ wastelist.wasteEntryID }}</li>
        <li>Quantity: {{ wastelist.quantity }}</li>
        <li>Disposalmethod: {{ wastelist.disposalmethod }}</li>
        <li>DonationID: {{ wastelist.donationID }}</li>
        <li>Organisation: {{ wastelist.organisation}}</li>
        <li>Attendees:
            {% for user in wastelist.attendees.all %}
        {{ user }}</br>
            {% endfor %}
        </li>
       </ul>
       </br/>
       {% endfor %}
    