objective_2/admin/urls.py
from django.contrib import admin
from django.urls import path

from .views import table_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tables/', table_list, name='table_list'),
]

objective_2/audit/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'audit'

urlpatterns = [
    path('', views.auditHome, name='auditHome'),

    path('login/', views.LoginView, name='login'),    
    path('logout/', views.LogoutView, name='logout'),    
    path('list/', views.list, name='list'),
    

    path('create/', views.create_waste_entry, name='create'),
    path('entries/<int:waste_entry_id>/delete/', views.delete_waste_entry, name='delete_entry'),
    path('entries/', views.waste_entries, name='entries'),

    path('items/<int:waste_entry_id>/create/', views.create_waste_item, name='create_item'),
    path('items/<int:waste_item_id>/delete/', views.delete_waste_item, name='delete_item'),
    path('items/<int:waste_entry_id>/', views.waste_items, name='items'),
    
    path('donate', views.donate, name='donate'),
   path('donate/past', views.donate_read, name = 'donate_read'),
    path('donate/update', views.donate_update, name = 'donate_update'),
    path('donate/delete', views.donate_delete, name = 'donate_delete'),
    path('', views.accounts, name='accounts'),
    path('recipes/', views.recipe_list, name='recipe_list'),
    path('add_food/',views.add_food,name='add_food'),
    path('recipefoodsave.html/',views.savefood,name='savefoodss'),
   # path('initiate-payment/', views.initiate_payment, name='initiate_payment'),
   # path('complete-payment/<int:payment_id>/', views.complete_payment, name='complete_payment'),
]

objective_2/objective_2/urls.py
from django.urls import include, path

urlpatterns = [
    path('admin_console/', include('admin_console.urls')),
    path('', include('users.urls')),
    path('audit/', include('audit.urls')),
    path('accounts/', include('audit.urls')),

]

objective_2/audit/models.py
from django import forms
from django.db import models
from django.contrib.auth import models as auth
from django.core.validators import MinLengthValidator, MinValueValidator
from django.utils.html import format_html

class WasteEntries(models.Model):
    wasteEntryID = models.AutoField(primary_key=True)
    userID = models.ForeignKey(
        auth.User,
        on_delete=models.CASCADE,
        db_column='userID'
    )
    date = models.DateField()

    class Meta:
        verbose_name_plural = "Waste Entries"

    def __str__(self):
        return f"{self.wasteEntryID}. {self.userID} ({self.date})"

class WasteItems(models.Model):
    wasteItemID = models.AutoField(primary_key=True)
    wasteEntryID = models.ForeignKey(WasteEntries, on_delete=models.CASCADE)
    itemDescription = models.CharField(max_length=64)
    quantity = models.FloatField(
        validators=[MinValueValidator(0)]
    )

    class Meta:
        verbose_name_plural = "Waste Items"

    def __str__(self):
        return f"{self.itemDescription}, {self.wasteEntryID.userID} ({self.wasteEntryID.date})"


class Organisation(models.Model):
    orgid = models.CharField('Organisation', primary_key=True, max_length = 30)    
    description= models.TextField(blank=True)
    orgtype = models.CharField('Organisation Type', null=True, max_length=90)
    
    
    def __str__(self):
        return self.orgid

class Donate(models.Model):
     userID= models.ForeignKey(auth.User, on_delete =models.CASCADE, db_column = 'userID')    # foreign key of userID in user table
     orgID= models.ForeignKey(Organisation, on_delete = models.CASCADE, db_column = 'orgid') # Foreigh  key of organisation id field
     amount = models.IntegerField('Amount(kg)') # Amount donated by the user (max is $9999999 for one donation)
     date = models.DateTimeField()
     def __str__(self):
        return str(self.userID)

# For getting the recipies from the waste produce 
class FoodForm(models.Model):
    nameofItem1 = models.CharField(max_length=100)
    quantity1 = models.IntegerField()
    nameofItem2 = models.CharField(max_length=100)
    quantity2 = models.IntegerField()
    nameofItem3 = models.CharField(max_length=100)
    quantity3 = models.IntegerField()
    
    def  __str__(self) -> str:
        return self.nameofItem1
    
class RecipesSaved(models.Model):
    Recipe=models.CharField(max_length=22200)
    
    def __str__(self):
        return self.Recipe  
    

objective_2/audit/forms.py
from django import forms
from .models import *


# Django's ModelForm
class DonationForm(forms.ModelForm):

    # model attributes (userID, orgID, amount)
    class Meta:
        model = Donate
        # The fields to be included in the form
      
        fields = ('userID','orgID', 'amount', 'date')
        widgets = {
                       'userID':forms.HiddenInput(), 
                  }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].widget = forms.DateInput(attrs={'type': 'date'})





        

class recipeForm(forms.ModelForm):
    class Meta:
        model = FoodForm
        fields = ('nameofItem1','quantity1','nameofItem2','quantity2','nameofItem3','quantity3')


class CreateWasteEntry(forms.ModelForm):
    class Meta:
        model = WasteEntries
        fields = ['userID', 'date']
        widgets = {'userID':forms.HiddenInput()}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].widget = forms.DateInput(attrs={'type': 'date'})


class WasteItemForm(forms.ModelForm):
    class Meta:
        model = WasteItems
        fields = ['itemDescription', 'quantity']

objective_2/audit/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import models as authmodels
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, timezone
from django.http import HttpResponse
from django.core import serializers
from .forms import CreateWasteEntry
from django.template import loader
from django.urls import reverse
from .models import *
from .forms import *
from .recipe import *
from . import utils



app_name = 'audit/'

# Create your views here

def LoginView(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is None:
            context = {"error": "Invalid username or password!"}
            return render(request, 'users/login.html',context)
        # send user to homepage and add user id to session 
        login(request,user)
        userid = getattr(user, 'id')
        request.session['id'] = userid
        homepage = reverse('audit:auditHome')
        return redirect(homepage)
    return render(request, 'users/login.html',{})    

def LogoutView(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/login/')
    return render(request, 'users/logout.html',{})



def auditHome(request):
    # if session is 0 return user to some view that they need to login
    return render(request, 'audit/AuditHomePage.html')

def waste_entries(request):
    entries = WasteEntries.objects.filter(userID = request.session['id'])
    return render(request, 'audit/waste_entries.html', {'entries': entries})

def waste_items(request, waste_entry_id):
    waste_entry = get_object_or_404(WasteEntries, pk=waste_entry_id)
    waste_items = WasteItems.objects.filter(wasteEntryID=waste_entry_id)
    return render(request, 'audit/waste_items.html', {'waste_entry': waste_entry, 'waste_items': waste_items})

def create_waste_entry(request):
    if request.method == 'POST':
        form = CreateWasteEntry(request.POST)
        if form.is_valid():
            entry = form.save()
            wasteid = getattr(entry, 'wasteEntryID')
            # redirect user to enter their waste items
            return redirect(f'/audit/items/{wasteid}/create/')  
            
    form = CreateWasteEntry(initial= {'userID':request.session['id']})
    
    return render(request, 'audit/create_waste_entry.html', {'form': form})

def delete_waste_entry(request, waste_entry_id):
    waste_entry = get_object_or_404(WasteEntries, pk=waste_entry_id)
    waste_entry.delete()
    return redirect('audit:entries')

def create_waste_item(request, waste_entry_id):
    waste_entry = get_object_or_404(WasteEntries, pk=waste_entry_id)

    if request.method == 'POST':
        form = WasteItemForm(request.POST)
        if form.is_valid():
            waste_item = form.save(commit=False)
            waste_item.wasteEntryID = waste_entry
            waste_item.save()
            return redirect('audit:items', waste_entry_id=waste_entry.wasteEntryID)
    else:
        form = WasteItemForm()

    return render(request, 'audit/add_waste_item.html', {'form': form, 'waste_entry': waste_entry})

def delete_waste_item(request, waste_item_id):
    waste_item = get_object_or_404(WasteItems, pk=waste_item_id)
    waste_item.delete()
    return redirect('audit:entries')



def list(request):
    try:
        request.session['id']
    except:
        return redirect('/login/')
    return render(request, 'audit/AuditHomepage.html')

def donate(request):
    error = 2
    if request.method == 'POST':
        form = DonationForm(request.POST)
        if form.is_valid():
            date = form.cleaned_data['date']
            if date.date() < datetime.now().date():
                error = 0
            else:
                error = 1
                form.save()
    
    form = DonationForm(initial=
        {
            'userID':authmodels.User.objects.get(id = request.session['id']),
        }
    )
    page_data = {'myform': form, 'error':error}

    return render(request, app_name + 'donate_create.html', page_data)

'''
Displays all donations made by user
'''

def donate_read(request):
    forms = []
    dates =[]
    donates = Donate.objects.all().filter(userID = request.session['id']).\
              filter(date__lt=datetime.now().date())  
    for model in donates:
        forms.append(DonationForm(instance = model))
        
    content = { 'donations': forms}    
    return render(request, app_name + 'donate_read.html', content)

'''
donate_update
'''
def donate_update(request):
    error = 2
    if request.method == 'POST':
        model = Donate.objects.get(id=request.POST.get('id'))   # get correct model instance
        form = DonationForm(request.POST, instance = model)
        if form.is_valid():
            error=0
            date = form.cleaned_data['date']
            if date.date() < datetime.now().date():
                error = 0
            else:
                error = 1
                form.save()    
    forms = []
    ids =[]
    donates = Donate.objects.all().filter(userID=request.session['id'])\
              .filter(date__gte=datetime.now().date())
    for model in donates:
        forms.append(DonationForm(instance = model))
        ids.append(getattr(model, 'id'))
    content = { 'donations': forms,
                'ids': ids,
                'error':error}    
    return render(request, app_name + 'donate_update.html', content)

def donate_delete(request):  
    if request.method == 'POST':
        Donate.objects.filter(pk=request.POST.get('id')).delete()   # get correct model instance
        
    
    forms = []
    ids =[]
    donates = Donate.objects.all().filter(userID=request.session['id'])
    for model in donates:
        forms.append(DonationForm(instance = model))
        ids.append(getattr(model, 'id'))
    content = { 'donations': forms,
                'ids': ids}    
    return render(request, app_name + 'donate_delete.html', content)


def accounts(request):
	return render(request, 'audit/accounts.html')
	
def waste_items_view(request, waste_entry_id):
    waste_items = utils.get_waste_items_by_entry_id(waste_entry_id)
    return render(request, 'audit/waste_items.html', {'waste_items': waste_items, 'waste_entry_id': waste_entry_id})

    
def add_food(request):
    page_data={'myForm':recipeForm(),}
    return render(request, 'audit/Recipes.html',page_data)

def savefood(request):
    if request.method == 'POST':
        form = recipeForm(request.POST)
        if form.is_valid():
            form.save()
        
        saved_data = FoodForm.objects.all()
        item1 = form.cleaned_data['nameofItem1']
        item2 = form.cleaned_data['nameofItem2']
        item3 = form.cleaned_data['nameofItem3']
        
        recipe = Recipe.generate_recipe(item1, item2, item3)
        
        recipes = RecipesSaved()
        recipes.Recipe = recipe
        recipes.save()
    
    return render(request, 'audit/recipefoodsave.html', {'Recipes': recipe})

def recipe_list(request):
    recipes = RecipesSaved.objects.all()
    return render(request, 'audit/recipe_list.html', {'recipes': recipes})

objective_2/audit/templates/audit/AuditHomepage.html
{% extends 'users/__base.html' %}

{% block title %}
<title>Audit Food Waste</title>
{% endblock%}

{% block content %}
<h1>Audit Food Waste</h1>   

<table>
    <td>Contents</td>
    <td><a href="{% url 'audit:create' %}" style="color: rgb(42, 55, 193);  text-decoration: none ;font-size: 2em;">Create Waste Entry</a></td>
    <td><a href="{% url 'audit:entries' %}" style="color: rgb(42, 55, 193); text-decoration: none ;font-size: 2em;">See existing Waste Entries</a></td>
    <td><a href="{% url 'audit:donate' %}" style="color: rgb(42, 55, 193);text-decoration: none ; font-size: 2em;">Donate extra food </a></td>
    <td><a href="{% url 'audit:donate_update' %}" style="color: rgb(42, 55, 193);text-decoration: none ; font-size: 2em;"> Update upcoming Donations </a></td>
    <td><a href="{% url 'audit:donate_read' %}" style="color: rgb(42, 55, 193); text-decoration: none ;font-size: 2em;">View past Donations</a></td>
    <td><a href="{% url 'audit:add_food' %}" style="color: rgb(42, 55, 193);text-decoration: none ; font-size: 2em;">Let ChatGPT give you some ideas/recipes to handle your waste food products </a></td>

</table>

{% endblock%}

objective_2/audit/templates/audit/Recipes.html
{% extends 'users/__base.html' %}
{% block title %}
<title>Recipes</title>
{% endblock%}
{% block content %}
Enter the Food that you may throw away, and see the what recipes you can make with them!
with leftover food, save the enviornemnt and save money!
    <form action="/audit/recipefoodsave.html/" method="post" >
        {% csrf_token %}
        <table>
          {{ myForm.as_table }}
        </table>
        <input type="submit" value="Genereate your Recipe" />
      </form>
{% endblock%}

objective_2/audit/templates/audit/accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Accounts</title>
</head>
<body>
    <h1>Accounts</h1>
</body>
</html>

objective_2/audit/templates/audit/add_waste_item.html
{% extends 'users/__base.html' %}

{% block title %}
<title>Create Waste Item</title>
{% endblock%}

{% block content %}
<h1>Create Waste Item</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>
<a href="javascript:history.back()">Cancel</a>
{% endblock%}

objective_2/audit/templates/audit/create_waste_entry.html
{% extends 'users/__base.html' %}

{% block title %}
<title>Create Waste Entry</title>
{% endblock%}

{% block content %}
<h1>Create Waste Entry</h1>
<form action = ""method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="javascript:history.back()">Cancel</a>
{% endblock%}

objective_2/audit/templates/audit/donate_create.html
{% extends 'users/__base.html' %}

{% block title %}
<title>Donate to Food Waste Organisation</title>
{% endblock%}

{% block content %}
<form action="donate" method="post">
    {% csrf_token %}
    <table>
        {{ myform.as_table }}
    </table>
    <input type="submit" value="Donate" />
</form>
    {% if error == 0 %}
<p style="color:red;"> Date must be in the future </p>
    {% elif error == 1 %}
<p style="color:green;"> Submitted </p>
    {% endif %}
<a href="{% url 'audit:auditHome' %}">Back to home</a>
{% endblock %}

objective_2/audit/templates/audit/donate_delete.html
{% extends 'users/__base.html' %}
{% load index %}

{% block title %}
<title>Delete Upcoming Donation</title>
{% endblock%}

{% block content %}
<a href="{% url 'audit:donate_read' %}">Back</a>
    {% for donation in donations %}
    <form action="delete" method="post">
        {% csrf_token %}
        <input type="text" name="id" value="{{ ids|index:forloop.counter0 }}" />
        <table>
            {{ donation.as_table }}
        </table>
        <input type="submit" value="Delete" />
    </form>
    {% endfor %}

{% endblock %}

objective_2/audit/templates/audit/donate_read.html
{% extends 'users/__base.html' %}

{% block title %}
<title>Past Donations</title>
{% endblock%}

{% block content %}
<a href="{% url 'audit:auditHome' %}">Back to home</a>
<a href="{% url 'audit:donate_delete' %}">Go to donation deletion</a>
    {% for donation in donations %}
<fieldset disabled="disabled">
    {{ donation.as_table }}
</fieldset>
    {% endfor %}
{% endblock %}

objective_2/audit/templates/audit/donate_update.html
{% extends 'users/__base.html' %}
{% load index %}

{% block title %}
<title>Update Upcoming Donations</title>
{% endblock%}

{% block content %}
<a href="{% url 'audit:auditHome' %}">Back to home</a>
    {% if error == 0 %}
<p style="color:red;"> Date must be in the future </p>
    {% elif error == 1 %}
<p style="color:green;"> Submitted </p>
    {% endif %}
    {% for donation in donations %}
<form action="update" method="post">
    {% csrf_token %}
    <input type="text" name="id" value="{{ ids|index:forloop.counter0 }}" readonly="readonly" />
    <table>
        {{ donation.as_table }}
    </table>
    <input type="submit" value="Donate" />
</form>
    {% endfor %}
    {% endblock %}

objective_2/audit/templates/audit/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Accounts</title>
</head>
<body>
    <h1>Accounts</h1>
</body>
</html>

objective_2/audit/templates/audit/login.html
{% extends "users/__base.html" %}
{% load static %}
{% load index %}


{% block content %}
        
        <div style='margin-top:30px;'>
            <form action="" method="post" id="loginform">
                {% csrf_token %}
                {% if error %}
                <p style='color:red'>{{ error }}</p>
                {% endif %}
            </div>
                <input type='text' name='username'
                    placeholder='username' />
                
                    <input type='password' name='password' placeholder='password' />
                    <button type="submit" form="loginform">Log in</button>
                </div>
                </form>
                
                
            </div>
       
            
    
{% endblock %}

objective_2/audit/templates/audit/recipe_list.html
{% extends "users/__base.html" %}
{% block title %}
<title>All Stored Recipes</title>
{% endblock %}

{% block content %}
<h1>All Stored Recipes</h1>

{% for recipe in recipes %}
    <p>{{ recipe }}</p>
{% endfor %}

{% endblock %}

objective_2/audit/templates/audit/waste_entries.html
{% extends 'users/__base.html' %}

{% block title %}
<title>Waste Entries</title>
{% endblock%}

{% block content %}
<h1>Waste Entries</h1>
<a href="{% url 'audit:create' %}">Create Waste Entry</a>
{% for entry in entries %}
    <h2>{{ entry.userID.username }}</h2>
    <p>{{ entry.wasteEntryID }}</p>
    <p>{{ entry.date }}</p>
    <a href="{% url 'audit:items' entry.wasteEntryID %}">View Waste Items</a>
    <a href="{% url 'audit:delete_entry' entry.wasteEntryID %}">Delete</a>
    <hr>
{% endfor %}
    <br />
    <a href="{% url 'audit:auditHome' %}">Back</a>
{% endblock%}

objective_2/audit/templates/audit/waste_items.html
{% extends 'users/__base.html' %}

{% block title %}
<title>Waste Items</title>
{% endblock%}

{% block content %}
<h1><u>Waste Entry Details</u></h1>
<p>Waste Entry ID: {{ waste_entry.wasteEntryID }}</p>
<p>User: {{ waste_entry.userID.username }}</p>
<p>Date: {{ waste_entry.date }}</p>

<a href="{% url 'audit:create_item' waste_entry.wasteEntryID %}">Add Waste Item</a>

<h2><u>Waste Items</u></h2>
<ul>
    {% for item in waste_items %}
        <li> Item: {{ item.itemDescription }}, Quantity: {{ item.quantity }} <a href="{% url 'audit:delete_item' item.wasteItemID %}">Delete</a></li>
    {% empty %}
        <li>No waste items found.</li>
    {% endfor %}
</ul>

<a href="{% url 'audit:entries' %}">Back to entries</a>
{% endblock%}